import Head from "next/head";

import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import MovieCard from "~/components/MovieCard";
import { useEffect, useState } from "react";

import { useQuery } from 'react-query';
import { type MovieResult } from "moviedb-promise";
import axios from 'axios';
import { type ExploreData, loadingMovies } from "~/lib/utils";

function Explore() {
	const [popular, setPopular] = useState<MovieResult[]>(loadingMovies);
    const [toprated, setToprated] = useState<MovieResult[]>(loadingMovies);
    const [nowplaying, setNowplaying] = useState<MovieResult[]>(loadingMovies);

    const exploreData = useQuery('exploreData', () =>
        axios.get('/api/explore').then(res => res.data as MovieResult[])
    , {
        refetchOnMount: false,
        refetchOnWindowFocus: false,
        refetchOnReconnect: false,
    });

    useEffect(() => {
        console.log(exploreData);
        if (!exploreData.isLoading && !exploreData.error) {

            console.log(exploreData.data);
            const movies = (exploreData.data as unknown as ExploreData);

            setPopular(movies.popular);
            setToprated(movies.toprated);
            setNowplaying(movies.nowplaying);
        }
    }, [exploreData]);

	return (
        <>
            <Head>
                <title>Moviie | Explore</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar selected="home" />
            <main id="app" className="page-container">
                <div className="h-10 w-full"></div>
                <div className="flex flex-col w-full py-16">
                    <p className="text-3xl font-bold pl-2 text-slate-700 select-none">Popular</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            popular.map((movie, index) => <MovieCard key={index} data={movie} />)
                        }
                        </div>
                    </div>

                    <p className="text-3xl font-bold pl-2 mt-8 text-slate-700 select-none">Top Rated</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            toprated.map((movie, index) => <MovieCard key={index} data={movie} />)
                        }
                        </div>
                    </div>

                    <p className="text-3xl font-bold pl-2 mt-8 text-slate-700 select-none">Now Playing</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            nowplaying.map((movie, index) => <MovieCard key={index} data={movie} />)
                        }
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </>);

}

export default Explore;