import Head from "next/head";
import Link from "next/link";

import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import MovieCard from "~/components/MovieCard";
import { useEffect, useState } from "react";

import { useQuery } from 'react-query';
import { type MovieResult } from "moviedb-promise";
import axios from 'axios';

function Explore() {
	const [popular, setPopular] = useState<MovieResult[]>([]);
    const [toprated, setToprated] = useState<MovieResult[]>([]);

    interface ExploreData {
        data: MovieResult[];
    }

    const popularData = useQuery('popular', () =>
        axios.get('/api/popular').then(res => res.data as MovieResult[])
    , {
        refetchOnMount: false,
        refetchOnWindowFocus: false,
        refetchOnReconnect: false,
    });

    const topRatedData = useQuery('toprated', () =>
        axios.get('/api/toprated').then(res => res.data as MovieResult[])
    , {
        refetchOnMount: false,
        refetchOnWindowFocus: false,
        refetchOnReconnect: false,
    });

    useEffect(() => {
        console.log(popularData);
        if (!popularData.isLoading && !popularData.error) {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
            console.log(popularData.data);
            const movies = (popularData.data as unknown as ExploreData).data ?? [];
            setPopular(movies);
        }

        if (!topRatedData.isLoading && !topRatedData.error) {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
            console.log(topRatedData.data);
            const movies = (topRatedData.data as unknown as ExploreData).data ?? [];
            setToprated(movies);
        }
    }, [popularData, topRatedData]);

	return (
        <>
            <Head>
                <title>Moviie | Explore</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar selected="home" />
            <main id="app" className="page-container">
                <div className="h-10 w-full"></div>
                <div className="flex flex-col w-full py-16">
                    <p className="text-3xl font-bold pl-4">Popular</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            popular.map((movie, index) => <MovieCard key={index} data={movie} />)
                        }
                        </div>
                    </div>

                    <p className="text-3xl font-bold pl-4 mt-8">Top Rated</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            toprated.map((movie, index) => <MovieCard key={index} data={movie} />)
                        }
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </>);

}

export default Explore;