import Head from "next/head";
import Link from "next/link";

import Footer from "~/components/Footer";
import Navbar from "~/components/Navbar";
import MovieCard from "~/components/MovieCard";
import { useState } from "react";


function Explore() {
    interface Movie {
        name: string,
        image: string
    }

	const [popular, setPopular] = useState<Movie[]>([]);
	const [loading, setLoading] = useState(true);

    

	return (
        <>
            <Head>
                <title>Moviie | Explore</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar selected="home" />
            <main id="app" className="page-container">
                <div className="h-10 w-full"></div>
                <div className="flex flex-col w-full py-16">
                    <p className="text-3xl font-bold pl-4">Popular</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            popular.map((movie, index) => <MovieCard key={index} name={movie.name} image={movie.image} />)
                        }
                        </div>
                    </div>

                    <p className="text-3xl font-bold pl-4 mt-8">Top Rated</p>
                    <div className="overflow-x-scroll">
                        <div className="flex w-fit">
                        {
                            movies.map((movie, index) => <MovieCard key={index} name={movie.name} image={movie.image} />)
                        }
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </>);

}

export default Explore;