import Head from "next/head";
import Link from "next/link";

import Navbar from "~/components/Navbar";

export default function Home() {
    return (
        <>
            <Head>
                <title>Moviie | Home</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="page-container">
                <Navbar selected="home" />
                <div className="h-10 w-full"></div>
                <div className="container flex flex-col justify-center w-full px-4 py-16 bg-red-200">
                    movies
                </div>
            </main>
        </>
    );
}
